stages:
  - test
  - build
  - deploy
unit-test:
  stage: test
  variables:
    ErrorActionPreference: Stop
  script:
    - Start-Process "C:\Program Files\Unity\Hub\Editor\2020.3.25f1\Editor\Unity.exe" -ArgumentList "-batchmode -projectPath . -runTests -testPlatform editmode -logFile -testResults unit-tests.xml" -Wait | Out-Default
    - '[xml]$xml = Get-Content -PATH unit-tests.xml'
    

unity-build:
  stage: build
  script: echo 'Building...'
  tags:
    - unity
playstore:
  stage: deploy
  script: echo 'Deploying...'
  tags:
    - unity