stages:
  - build
  - EditTest
  - PlayTest

build-job:
  stage: build
  script:
    - mkdir .\ece651Project\builds
    - cd .\ece651Project\
    - Unity.exe -quit -batchmode -logfile buildLog.xml -executeMethod BuildScript.PerformBuild | Out-Default
  artifacts:
    paths:
      - .\buildLog.xml
    expire_in: 3 days

EditModetest-job:
  stage: EditTest
  
  script:
    - Unity.exe -runTests -testPlatform editmode -batchmode -projectPath . -testResults -logFile  EditmodeResults.xml | Out-Default

  artifacts:
    paths: 
      - .\ece651Project\EditmodeResults.xml 
    expire_in: 3 days

PlayModetest-job:
  stage: PlayTest
  
  script:
    - Unity.exe -runTests -batchmode -testPlatform playmode -projectPath ./ece651Project  -logFile -testResults ./PlaymodeResults.xml | Out-Default
  
  artifacts:
    paths: 
      - .\ece651Project\PlaymodeResults.xml 
    expire_in: 3 days