stages:
  - build
  - EditTest
  - PlayTest

build-job:
  stage: build
  script:
    - echo "Not yet implemented"

EditModetest-job:
  stage: EditTest
  
  script:
    - cd .\ece651Project\
    - Unity.exe -runTests -testPlatform editmode -batchmode -projectPath . -testResults -logFile  EditmodeResults.xml | Out-Default

PlayModetest-job:
  stage: PlayTest
  
  script:
    - Unity.exe -runTests -batchmode -testPlatform playmode -projectPath ./ece651Project  -logFile -testResults ./PlaymodeResults.xml | Out-Default
  
  artifacts:
    paths: 
      - .\ece651Project\PlaymodeResults.xml 
    expire_in: 1 week