stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Hello, World"

EditModetest-job:
  stage: test
  
  script:
    - Unity.exe -runTests -batchmode -testPlatform editmode -projectPath ./ece651Project  -logFile -testResults ./EditmodeResults.xml -Wait | Out-Default

PlayModetest-job:
  stage: test
  
  script:
    - Unity.exe -runTests -batchmode -testPlatform playmode -projectPath ./ece651Project  -logFile -testResults ./PlaymodeResults.xml -Wait | Out-Default